# Autogenerated by nbdev

d = { 'settings': { 'branch': 'a',
                'doc_baseurl': '/proyecto',
                'doc_host': 'https://a.github.io',
                'git_url': 'https://github.com/a/proyecto',
                'lib_path': 'proyecto'},
  'syms': {'proyecto.core': {'proyecto.core.foo': ('core.html#foo', 'proyecto/core.py')}}}
